language: ruby
cache: bundler

rvm:
  - "1.9.3"
  - "2.0.0"
  - "2.1.1"

#script: 'bundle exec rake'

notifications:
  email:
    recipients:
      - yuri.veremeyenko@email.com
    on_failure: change
    on_success: never